$schema: 'https://moonrepo.dev/schemas/tasks.json'

implicitInputs:
  - 'Cargo.toml'

implicitDeps:
  - "^:build"

fileGroups:
  cargo:
    - 'Cargo.toml'
    - 'crates/*/src/**/*'
    - 'crates/*/Cargo.toml'
    # - '/.cargo/config.toml'
    - '/rust-toolchain.toml'
  sources: []
  tests:
    - 'crates/*/benches/**/*'
    - 'crates/*/tests/**/*'

tasks:
  cargo:
    command: 'cargo'
    local: true
    env: &env
      CARGO_TERM_COLOR: 'always'

  check:
    command: 'cargo check --workspace --all-targets'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
      - '@group(tests)'
    env: *env

  format: &format
    command: 'cargo fmt --all --check'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
      - '@group(tests)'
      - '/rustfmt.toml'
    env: *env

  format-write:
    <<: *format
    command: 'cargo fmt --all -- --emit=files'
    local: true

  lint: &lint
    command: 'cargo clippy --workspace --all-targets'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
      - '@group(tests)'
      - '/clippy.toml'
    env: *env

  lint-fix:
    <<: *lint
    command: 'cargo clippy --workspace --all-targets --fix --allow-dirty --allow-staged'
    local: true
