$schema: 'https://moonrepo.dev/schemas/tasks.json'

extends: './tag-rust-base.yml'


tasks:
  build:
    command: 'wasm-pack build --release'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
    env: &env
      CARGO_TERM_COLOR: 'always'
    deps:
      - "~:build-no-modules"
  build-no-modules:
    command: 'wasm-pack build --target web --scope no-modules --out-dir no-modules'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
    env: &env
      CARGO_TERM_COLOR: 'always'
  test-web:
    command: 'wasm-pack test --firefox --headless'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
      - '@group(tests)'
      - '/.config/nextest.*'
    env: *env
    options:
      runInCI: true

  test-node:
    command: "wasm-pack test --node"
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
      - '@group(tests)'
      - '/.config/nextest.*'
    env: *env
    options:
      runInCI: true

  test:
    command: 'nextest run'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
      - '@group(tests)'
      - '/.config/nextest.*'
    env: *env
    deps:
      - "~:test-web"
      - "~:test-node"
    options:
      runDepsInParallel: false
