$schema: "https://moonrepo.dev/schemas/tasks.json"

implicitDeps:
  - "^:build"

implicitInputs:
  - "package.json"

fileGroups:
  # Application specific files
  app: []
  configs:
    - "*.{js,json,yml,yaml}"
  sources:
    - "public/**/*"
    - "src/**/*"
    - "types/**/*"
  tests:
    - "tests/**/*.test.*"
    - "tests/**/*.stories.*"
    - "**/__tests__/**/*"
  assets:
    - "assets/**/*"
    - "images/**/*"
    - "static/**/*"
    - "**/*.{scss,css}"
    - "**/*.{md,mdx}"

tasks:
  # https://moonrepo.dev/docs/guides/examples/prettier
  format:
    command:
      - "prettier"
      - "--ignore-path"
      - "@in(0)"
      - "--check"
      - "."
    inputs:
      - "/.prettierignore"
      - "/prettier.config.js"
      - "@group(app)"
      - "@globs(sources)"
      - "@globs(tests)"
      - "@globs(configs)"
      - "**/*.{md,mdx}"

  format-write:
    command:
      - "prettier"
      - "--ignore-path"
      - "@in(0)"
      - "--write"
      - "."
    inputs:
      - "/.prettierignore"
      - "/prettier.config.js"
      - "@group(app)"
      - "@globs(sources)"
      - "@globs(tests)"
      - "@globs(configs)"
      - "**/*.{md,mdx}"
    local: true

  # https://moonrepo.dev/docs/guides/examples/eslint
  lint: 
    command:
      - 'eslint'
      - '.'
    inputs: &lint
      - '*.config.*'
      - '**/.eslintrc.*'
      - '/.eslintrc.*'
      - 'tsconfig.json'
      # - '/tsconfig.eslint.json'
      - '/tsconfig.options.json'
      - '@group(app)'
      - '@globs(sources)'
      - '@globs(tests)'

  lint-fix: 
    command:
      - 'eslint'
      - '.'
      - '--fix'
    inputs: *lint
    local: true

  # https://moonrepo.dev/docs/guides/examples/jest
  test:
    command:
      - "jest"
      - "--passWithNoTests"
      - "--preset"
      - "jest-preset-moon"
    inputs:
      - "@globs(sources)"
      - "@globs(tests)"
      - "jest.config.*"

  # https://moonrepo.dev/docs/guides/examples/typescript
  typecheck:
    command:
      - "tsc"
      - "--build"
    deps:
      - '^:build'
    inputs:
      - "@group(app)"
      - "@globs(sources)"
      - "@globs(tests)"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "/tsconfig.options.json"
