$schema: 'https://moonrepo.dev/schemas/tasks.json'


extends: "./tag-rust-base.yml"


tasks:
  
  build: &build
    command: 'cargo build'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
    env: &env
      CARGO_TERM_COLOR: 'always'

  build-release:
    <<: *build
    command: 'cargo build --release'
    local: true

  test:
    command: 'nextest run'
    inputs:
      - '@group(cargo)'
      - '@group(sources)'
      - '@group(tests)'
      - '/.config/nextest.*'
    env: *env